### PR TITLE
Get pipeline working

### PR DESCRIPTION
**Pull request by wtgodbe**
Hooks us up to build this repo publicly and internally in azdo

### CODE REVIEW

**Comment by wtgodbe** [comment]
It worked! This got triggered: https://dev.azure.com/dnceng/public/_build/results?buildId=941929&view=results

It'll fail until https://github.com/aspnet/jquery-validation-unobtrusive/pull/131 is in

**Comment by wtgodbe** [comment]
I brought in the changes from https://github.com/aspnet/jquery-validation-unobtrusive/pull/131, so this is working now. It builds and uploads jquery-validation-unobtrusive-3.2.12.tgz and Microsoft.jQuery.Unobtrusive.Validation.3.2.12.nupkg

**Review by mkArtakMSFT — APPROVED** [review]
Thanks @wtgodbe !

**Comment by wtgodbe** [comment]
The build isn't approved for signing yet, I'll try again tomorrow.

**Comment by wtgodbe** [comment]
Still not authorized - I'm escalating in the first responders Teams channel.

**Comment by wtgodbe** [comment]
Got a green build! https://dev.azure.com/dnceng/internal/_build/results?buildId=945081&view=results

I verified that it signed the .nupkg and the .js files inside.

**Pull request merged**
