### PR TITLE
Merge from internal & fixup .npmrc

### PR DESCRIPTION
**Pull request by wtgodbe**
Merged in the missing internal commit, and then updated the file as per https://github.com/dotnet/arcade-services/pull/1924/files

### CODE REVIEW

**Comment by wtgodbe** [comment]
I believe merge-committing this will unblock the mirror (CC @dougbu)

**Comment by dougbu** [comment]
This apparently isn't a solution when building in public. /cc @mmitche 

``` text
C:\Program Files\dotnet\sdk\6.0.301\MSBuild.dll -consoleloggerparameters:Summary -maxcpucount -property:SignType= -property:Configuration=Release -restore -verbosity:m /bl:artifacts/logs/build.binlog .\build.proj
  Determining projects to restore...
  Restored D:\a\1\s\build.proj (in 182 ms).
  npm WARN jquery-validation-unobtrusive@3.2.12 license should be a valid SPDX license expression
  
  npm ERR! code E401
  npm ERR! Unable to authenticate, your authentication token seems to be invalid.
  npm ERR! To correct this please trying logging in again with:
  npm ERR!     npm login
  
  npm ERR! A complete log of this run can be found in:
  npm ERR!     C:\npm\cache\_logs\2022-06-28T16_08_19_154Z-debug.log
D:\a\1\s\build.proj(30,9): error MSB3073: The command "npm install" exited with code 1.
```

**Comment by dougbu** [comment]
We have a few warnings that could be addressed here or later:

``` text
  npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
...
EXEC : warning : NU5125: The 'licenseUrl' element will be deprecated. Consider using the 'license' element instead. [D:\a\1\s\build.proj]
EXEC : warning : NU5048: The 'PackageIconUrl'/'iconUrl' element is deprecated. Consider using the 'PackageIcon'/'icon' element instead. Learn more at https://aka.ms/deprecateIconUrl [D:\a\1\s\build.proj]
```

The first is a simple change to build.proj, as the warning suggests.

The second is pretty simple too:  `<license type="expression">MIT</license>`.

I also recommend using `"license": "MIT"` in the package.json file. (It also feels odd that the license here is the MIT URI while the `npm` package points to <https://aka.ms/jqueryunobtrusivelicense>. That URI redirects back to <https://github.com/aspnet/jquery-validation-unobtrusive/blob/main/LICENSE.txt> and displays the MIT license content but why have the indirection❔ Using the license expression in both places would be better.)

The last one requires a slight change to the .nuspec to add the icon file (which isn't in the repo yet) and doing the right stuff to reference it. We have done that elsewhere, even w/o Arcade's help (though that does make it much easier.)

**Review by dougbu — APPROVED** [review]

**Pull request merged**
